language: r
sudo: false
cache: packages
warnings_are_errors: true

r_packages:
  - covr

r_github_packages:
  - jimhester/lintr

before_install:
  - R -e 'source("https://install-github.me/r-lib/remotes")'
  
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()' 
  - Rscript -e 'covr::codecov()'

r:
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change