language: r
r: bioc-devel
sudo: false
cache:
  packages: true
warnings_are_errors: true

r_packages:
  - covr
  - knitr
  - roxygen2

r_github_packages:
  - jimhester/lintr

before_install:
  - R -e 'source("https://install-github.me/r-lib/remotes")'
  
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()' 
  - Rscript -e 'covr::codecov()'



notifications:
  email:
    recipients: thomasnaake@gmail.com
    on_success: change
    on_failure: change